image: Previous Ubuntu1804
install:
- sh: >-
    sudo apt-get -y update
- sh: >-
    sudo apt-get -y install repo gawk wget git diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping libsdl1.2-dev xterm
- sh: >-
    git config --global color.ui false
cache:
- buildhistory
- cache
- sstate-cache
build_script:
- sh: >-
    repo init -u https://github.com/fgretief/angstrom-manifest -b angstrom-v2019.06-warrior
- sh: >-
    repo sync
- sh: >-
    MACHINE=raspberrypi source ./setup-environment
- sh: >-
    MACHINE=raspberrypi bitbake core-image-minimal
