name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare environment
      run: |
        sudo apt-get -y update
        sudo apt-get -y install repo gawk wget git diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping libsdl1.2-dev xterm
        git config --global color.ui false
    - name: Initialise source tree
      run: |
        repo init -u https://github.com/fgretief/angstrom-manifest -b angstrom-v2019.06-warrior
        repo sync
    - name: Initialise source tree
      run: |
        MACHINE=raspberrypi source ./setup-environment
        MACHINE=raspberrypi bitbake core-image-minimal
